# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwEWZdbiQYQGGJlqNFqaxt3LdYJn7hdb
"""

# --- ส่วนการ Patch แก้ปัญหา Error (ต้องอยู่บนสุด) ---
import sklearn.compose._column_transformer
class _RemainderColsList(list): pass
sklearn.compose._column_transformer._RemainderColsList = _RemainderColsList
# ----------------------------------------------

import streamlit as st
import pandas as pd
import joblib

# 1. โหลดโมเดล
model = joblib.load('diabetes_prediction_ultimate_model.pkl')

# 2. การตกแต่งหน้าเว็บ (UI Enhancement)
st.set_page_config(page_title="Diabetes AI Predictor", page_icon="🩺", layout="centered")

# Custom CSS เพื่อความสวยงาม
st.markdown("""
    <style>
    .reportview-container { background: #f0f2f6; }
    .main-title { font-size: 40px; font-weight: 800; color: #2C3E50; text-align: center; margin-bottom: 10px; }
    .disclaimer-box { font-size: 12px; color: #7F8C8D; background-color: #FDFEFE; padding: 15px; border-radius: 10px; border: 1px solid #EAECEE; margin-top: 30px; }
    </style>
    """, unsafe_allow_html=True)

st.markdown('<p class="main-title">🩺 Diabetes AI Predictor</p>', unsafe_allow_html=True)
st.markdown("<p style='text-align: center;'>ระบบพยากรณ์ความเสี่ยงโรคเบาหวานด้วยปัญญาประดิษฐ์</p>", unsafe_allow_html=True)
st.divider()

# 3. ส่วน Disclaimer (ประกาศคำเตือน)
with st.expander("⚠️ ข้อตกลงและคำปฏิเสธความรับผิดชอบ (Medical Disclaimer)"):
    st.write("""
    1. **ไม่ใช่การวินิจฉัยทางการแพทย์:** ผลลัพธ์จากแอปพลิเคชันนี้เป็นการพยากรณ์เชิงสถิติจากโมเดล Machine Learning เท่านั้น ไม่สามารถใช้ทดแทนการวินิจฉัยโดยแพทย์ผู้เชี่ยวชาญได้
    2. **ความแม่นยำ:** แม้โมเดลจะมีค่าความแม่นยำสูง (92%) แต่ผลลัพธ์อาจมีความคลาดเคลื่อนตามปัจจัยเฉพาะบุคคล
    3. **การนำไปใช้:** ห้ามใช้ผลลัพธ์นี้ในการปรับเปลี่ยนขนาดยาหรือการรักษาด้วยตนเอง โปรดปรึกษาบุคลากรทางการแพทย์ทุกครั้งก่อนตัดสินใจเรื่องสุขภาพ
    """)

# 4. เมนูเลือกโหมดการตรวจ
tab_std, tab_adv = st.tabs(["🏥 ตรวจเบื้องต้น (Standard)", "🔬 ตรวจละเอียด (Advanced)"])

# --- ฟังก์ชันหลักในการแสดงผลลัพธ์ ---
def show_result(data_dict):
    df_input = pd.DataFrame([data_dict])
    prediction = model.predict(df_input)[0]
    probability = model.predict_proba(df_input)[0][1]

    st.markdown("---")
    st.subheader("📊 ผลการวิเคราะห์")

    if prediction == 1:
        st.error(f"**ตรวจพบความเสี่ยงสูง** (โอกาส {probability:.2%})")
        st.markdown("""
        **🔍 สิ่งที่ควรทำต่อไป:**
        * นัดหมายพบแพทย์เพื่อตรวจเลือด (Fasting Blood Glucose / HbA1c)
        * ควบคุมปริมาณน้ำตาลและคาร์โบไฮเดรตในอาหาร
        * บันทึกอาการผิดปกติ (ถ้ามี) เช่น หิวน้ำบ่อย หรือปัสสาวะบ่อยผิดปกติ
        """)
    else:
        st.success(f"**ความเสี่ยงต่ำ** (โอกาส {probability:.2%})")
        st.markdown("""
        **✨ ข้อแนะนำในการรักษาสุขภาพ:**
        * ตรวจสุขภาพประจำปีอย่างสม่ำเสมอ
        * รักษาน้ำหนักตัวให้อยู่ในเกณฑ์มาตรฐาน (BMI 18.5 - 22.9)
        * ออกกำลังกายแบบคาร์ดิโออย่างน้อย 150 นาทีต่อสัปดาห์
        """)

# --- โหมด Standard (บุคคลทั่วไป) ---
with tab_std:
    st.markdown("### ข้อมูลทั่วไปและพฤติกรรม")
    c1, c2 = st.columns(2)
    with c1:
        age = st.number_input("อายุ (Age)", 1, 120, 30, help="อายุที่เพิ่มขึ้นส่งผลต่อความเสื่อมของตับอ่อนในการผลิตอินซูลิน")
        bmi = st.number_input("ดัชนีมวลกาย (BMI)", 10.0, 60.0, 25.0, help="คำนวณจาก น้ำหนัก(กก.) / ส่วนสูง(ม.) ยกกำลังสอง")
    with c2:
        activity = st.number_input("การออกกำลังกาย (นาที/สัปดาห์)", 0, 2000, 150, help="การขยับร่างกายช่วยให้เซลล์ดึงน้ำตาลไปใช้เป็นพลังงานได้ดีขึ้น")
        family = st.selectbox("ประวัติครอบครัว", ["ไม่มีญาติสายตรงเป็นเบาหวาน", "มีญาติสายตรงเป็นเบาหวาน"], help="พันธุกรรมมีส่วนสำคัญในการถ่ายทอดความเสี่ยงเบาหวาน")

    if st.button("ประเมินความเสี่ยง (Standard Mode)", type="primary"):
        data = {
            'age': age, 'bmi': bmi, 'physical_activity_minutes_per_week': activity,
            'family_history_diabetes': 1 if "มี" in family else 0,
            'systolic_bp': 120, 'glucose_fasting': 95, 'hba1c': 5.4, 'ldl_cholesterol': 110 # ค่า Default
        }
        show_result(data)

# --- โหมด Advanced (มีผลเลือด) ---
with tab_adv:
    st.markdown("### ข้อมูลสุขภาพและผลทางห้องปฏิบัติการ")
    a1, a2 = st.columns(2)
    with a1:
        age_a = st.number_input("อายุ", 1, 120, 30, key="a_age")
        bmi_a = st.number_input("BMI", 10.0, 60.0, 25.0, key="a_bmi")
        act_a = st.number_input("ออกกำลังกาย (นาที/สัปดาห์)", 0, 2000, 150, key="a_act")
        fam_a = st.selectbox("ประวัติครอบครัว", ["ไม่มี", "มี"], key="a_fam")
    with a2:
        sys_a = st.number_input("ความดันตัวบน (Systolic BP)", 80, 250, 120, help="ความดันโลหิตสูงมักมาคู่กับภาวะดื้ออินซูลิน")
        glu_a = st.number_input("น้ำตาลก่อนอาหาร (Fasting Glucose)", 50, 500, 100, help="ระดับน้ำตาลหลังอดอาหาร 8 ชม. (หน่วย: mg/dL)")
        hba1c_a = st.number_input("น้ำตาลสะสม (HbA1c)", 3.0, 15.0, 5.5, help="ค่าน้ำตาลเฉลี่ยสะสมในเลือดช่วง 3 เดือนที่ผ่านมา (แม่นยำสูง)")
        ldl_a = st.number_input("ไขมันเลว (LDL Cholesterol)", 50, 300, 130, help="ระดับไขมันชนิดไม่ดีในเส้นเลือด")

    if st.button("วิเคราะห์เชิงลึก (Advanced Mode)", type="primary"):
        data = {
            'age': age_a, 'bmi': bmi_a, 'physical_activity_minutes_per_week': act_a,
            'family_history_diabetes': 1 if fam_a == "มี" else 0,
            'systolic_bp': sys_a, 'glucose_fasting': glu_a, 'hba1c': hba1c_a, 'ldl_cholesterol': ldl_a
        }
        show_result(data)

# --- ส่วนล่างสุดของหน้าเว็บ ---
st.markdown("""
    <div class="disclaimer-box">
        <b>หมายเหตุ:</b> แอปพลิเคชันนี้จัดทำขึ้นเพื่อเป็นส่วนหนึ่งของโครงงานการศึกษาด้าน Data Science
        โดยใช้ข้อมูลชุด Diabetes Dataset (Synthetic) ในการฝึกสอนโมเดลพยากรณ์
    </div>
    """, unsafe_allow_html=True)