# -*- coding: utf-8 -*-
"""Diabetes Predictor App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_D3hGCKdBOqrRmL45mlj8c35u4uF7H8
"""

# -*- coding: utf-8 -*-

import sklearn.compose._column_transformer
class _RemainderColsList(list): pass
sklearn.compose._column_transformer._RemainderColsList = _RemainderColsList

import streamlit as st
import pandas as pd
import joblib

# --- UI Setup ---
st.set_page_config(page_title="Diabetes AI Predictor", page_icon="🩺", layout="centered")

st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&family=Kanit:wght@300;400;600&display=swap');
    html, body, [class*="css"] { font-family: 'Inter', 'Kanit', sans-serif; background-color: #f8f9fa; }
    .main-title { font-size: 42px; font-weight: 800; color: #0f172a; text-align: center; margin-top: -40px; margin-bottom: 8px; }
    .sub-title { font-size: 16px; color: #64748b; text-align: center; margin-bottom: 40px; }
    .stButton > button { width: 100%; border-radius: 12px; height: 52px; background-color: #2563eb; color: white; font-weight: 600; border: none; }
    .result-container { background-color: white; padding: 24px; border-radius: 20px; border-left: 6px solid #2563eb; margin-top: 30px; box-shadow: 0 10px 20px -5px rgba(0, 0, 0, 0.05); }
    .metric-value { font-size: 48px; font-weight: 800; color: #2563eb; }
    </style>
    """, unsafe_allow_html=True)

st.markdown('<div class="main-title">🩺 Diabetes AI</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-title">ระบบวิเคราะห์ความเสี่ยงเบาหวานด้วย Gradient Boosting</div>', unsafe_allow_html=True)

@st.cache_resource
def load_models():
    try:
        return joblib.load('diabetes_model_standard.pkl'), joblib.load('diabetes_model_advanced.pkl')
    except: return None, None

model_std, model_adv = load_models()

def predict_and_display(input_data, active_model):
    input_df = pd.DataFrame([input_data])
    is_standard = len(input_data) == 3

    try:
        class_1_index = list(active_model.classes_).index(1)
        raw_prob = active_model.predict_proba(input_df)[0][class_1_index] * 100

        # Risk Normalization
        if is_standard:
            prob = ((raw_prob - 35.0) / (100.0 - 35.0)) * 100
            prob = max(1.0, min(99.0, prob))
        else:
            prob = raw_prob

        st.markdown(f'<div class="result-container"><div style="color:#64748b;font-weight:600;">โอกาสความเสี่ยง</div><div class="metric-value">{prob:.2f}%</div></div>', unsafe_allow_html=True)

        high, med = (60, 25) if is_standard else (70, 30)
        if prob >= high: st.error("⚠️ **ความเสี่ยงสูง:** ควรพบแพทย์เพื่อตรวจสุขภาพอย่างละเอียด")
        elif prob >= med: st.warning("🟡 **ความเสี่ยงปานกลาง:** ควรปรับพฤติกรรมการทานอาหาร")
        else: st.success("✅ **ความเสี่ยงต่ำ:** สุขภาพของคุณยังอยู่ในเกณฑ์ดี")

        # แสดงชื่อ Algorithm
        algo = active_model.named_steps['classifier'].__class__.__name__
        st.caption(f"🧠 Engine: {algo} | Recall Optimization")

    except Exception as e: st.error(f"Error: {e}")

tab1, tab2 = st.tabs(["✨ โหมดมาตรฐาน", "🧪 โหมดเชิงลึก"])

with tab1:
    st.markdown("##### 📝 ข้อมูลร่างกายเบื้องต้น")
    c1, c2 = st.columns(2)
    with c1:
        age_s = st.number_input("อายุ", 1, 100, 30, key="s_age")
        weight_s = st.number_input("น้ำหนัก (กก.)", 30.0, 200.0, 70.0, key="s_weight")
    with c2:
        height_s = st.number_input("ส่วนสูง (ซม.)", 100.0, 250.0, 170.0, key="s_height")
        act_s = st.number_input("ออกกำลังกาย (นาที/สัปดาห์)", 0, 1000, 150, key="s_act")

    bmi_s = weight_s / ((height_s / 100) ** 2)
    st.info(f"💡 BMI: {bmi_s:.2f}")

    if st.button("วิเคราะห์ความเสี่ยง", key="btn_std"):
        predict_and_display({'age': age_s, 'bmi': bmi_s, 'physical_activity_minutes_per_week': act_s}, model_std)

with tab2:
    st.markdown("##### 🔬 ข้อมูลทางห้องปฏิบัติการ")
    a_col1, a_col2 = st.columns(2)
    with a_col1:
        age_a = st.number_input("อายุ", 1, 100, 30, key="a_age")
        weight_a = st.number_input("น้ำหนัก", 30.0, 200.0, 70.0, key="a_weight")
        height_a = st.number_input("ส่วนสูง", 100.0, 250.0, 170.0, key="a_height")
        act_a = st.number_input("ออกกำลังกาย", 0, 1000, 150, key="a_act")
        fam_a = st.selectbox("ประวัติครอบครัว", ["ไม่มี", "มี"], key="a_fam")
    with a_col2:
        sys_a = st.number_input("ความดันตัวบน", 80, 200, 120)
        glu_a = st.number_input("น้ำตาลก่อนอาหาร", 50, 400, 100)
        hba1c_a = st.number_input("น้ำตาลสะสม", 3.0, 15.0, 5.5)
        ldl_a = st.number_input("ไขมันเลว", 50, 300, 130)

    if st.button("เริ่มการวิเคราะห์เชิงลึก", key="btn_adv"):
        predict_and_display({
            'age': age_a, 'bmi': weight_a/((height_a/100)**2), 'physical_activity_minutes_per_week': act_a,
            'family_history_diabetes': 1 if fam_a == "มี" else 0, 'systolic_bp': sys_a,
            'glucose_fasting': glu_a, 'hba1c': hba1c_a, 'ldl_cholesterol': ldl_a
        }, model_adv)